import React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Header from "./header";
import "@/styles/globals.css";
import { Footer } from "@/components";
import { Toaster } from "sonner";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toaster />
        <Header />
        <main className="min-h-screen main_footer_container z-10">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
