export { default as Features } from "./features";
export { default as HomeComponent } from "./home";
export { default as Footer } from "./footer";
export { default as Portfolio } from "./portfolio";
export { default as SectionContainer } from "./sectionContainer";
export { default as Resume } from "./resume";
export { default as Contact } from "./contact";
export { default as FindWithMe } from "./findWithMe";
export { default as ProgressBar } from "./progressBar";
